sonar.projectKey=devforge-flask
sonar.projectName=DevForge Flask
sonar.sources=.
sonar.tests=tests
sonar.python.version=3.14

sonar.exclusions=**/.venv/**,**/__pycache__/**,**/*.pyc
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
